

LISTEN_PORT = 8080

PLAYER_SLEEP_SECONDS = 0.5
FS_RECORDED_TRACK_PERIOD = 0.25
PLAYER_POINTER_INCREMENT = int(PLAYER_SLEEP_SECONDS / FS_RECORDED_TRACK_PERIOD)

PREDICTION_SLEEP_SECONDS = 2


MYSTATE_CHANNEL_NAME = 'my-state-updated'
ITEM_MY_STATE = 'myState'
ITEM_TRAFFIC = 'traffic'

SCENARIO_INFO_FILENAME = 'scenario_info.json'
SCENARIOS_FOLDER = "./scenarios"

